---
- name: Create application directory
  file:
    path: /opt/simple-app
    state: directory
    mode: "0755"

- name: Copy project files to server
  ansible.builtin.synchronize:
    src: "{{ playbook_dir }}/../"
    dest: /opt/simple-app/
    rsync_opts:
      - "--exclude=ansible"
      - "--exclude=.git"
      - "--exclude=.venv"
      - "--exclude=__pycache__"


- name: Start Docker Compose
  command: docker compose up -d
  args:
    chdir: /opt/simple-app

- name: Check container
  command: docker ps

- name: Check health endpoint
  uri:
    url: http://localhost:5000/health
    status_code: 200