---
- name: Create application directory
  file:
    path: /opt/simple-app
    state: directory
    mode: "0755"

- name: Ensure project exists
  stat:
    path: "{{ playbook_dir }}/../docker-compose.yml"

- name: Start Docker Compose
  command: docker compose up -d --build
  args:
    chdir: /opt/simple-app

- name: Check container
  command: docker ps

- name: Check health endpoint
  uri:
    url: http://localhost:5000/health
    status_code: 200