name: CI

on:
  push:
    branches:
      - main
  pull_request:


permissions:
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код репозитория
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Установить uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Установить зависимости
        run: uv sync

      - name: Запустить ruff
        run: uv run ruff check .

      - name: Запустить тесты
        run: uv run python -m pytest

      - name: Проверить shell-скрипты (Встроенный)
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          find . -name "*.sh" -exec shellcheck {} +